/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.empsystem.ui.panel.staff;


import com.empsystem.entity.PanelStore;
import com.empsystem.entity.SearchSelection;
import com.empsystem.ui.BasePanel;
import com.empsystem.ui.frame.SubFrame;
/**
 *
 * @author Michael
 */
public class StaffMainPanelUI extends BasePanel {
          
    /**
     * Creates new form StaffMain
     * @param ps
     */
    public StaffMainPanelUI(PanelStore ps) {        
        super(ps);     
    } 
       
    @Override
    public void init() {
        initComponents();  
    }
    
    @Override
    public void setupPage() {
       refreshTaskTable();
       
    }
    
    
    public void refreshTaskTable(){
        cleanTableModel(taskTable);
        getStaffTaskTableModel(projectDao.taskListForProjectMember(loginEmployee.getEmployee_no(),SearchSelection.ALL, null) ,taskTable);
        System.out.println("Task Table refreshed");
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logoutBotton = new javax.swing.JButton();
        personalInfoBotton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        taskTable = new javax.swing.JTable();
        refreshButton = new javax.swing.JButton();
        deptMemberSearchComboBox = new javax.swing.JComboBox<>();
        searchDepartmentTextField = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1627, 847));
        setMinimumSize(new java.awt.Dimension(1292, 675));
        setPreferredSize(new java.awt.Dimension(1292, 675));

        logoutBotton.setText("Logout");
        logoutBotton.setActionCommand("logoutBotton");
        logoutBotton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutBottonMouseClicked(evt);
            }
        });
        logoutBotton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBottonActionPerformed(evt);
            }
        });

        personalInfoBotton.setText("Personal INFO");
        personalInfoBotton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                personalInfoBottonMouseClicked(evt);
            }
        });
        personalInfoBotton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personalInfoBottonActionPerformed(evt);
            }
        });

        taskTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Project ID", "Task ID", "Project Name", "Project Leader", "Emp No", "Start Date", "End Date", "Duration", "Task Description"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(taskTable);

        refreshButton.setText("Refresh");
        refreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshButtonActionPerformed(evt);
            }
        });

        deptMemberSearchComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ALL", "Project ID", "Project Name", "Project Leader ID", "Project Still Processing", "Project Ended" }));
        deptMemberSearchComboBox.setPreferredSize(new java.awt.Dimension(148, 23));
        deptMemberSearchComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deptMemberSearchComboBoxActionPerformed(evt);
            }
        });

        searchDepartmentTextField.setPreferredSize(new java.awt.Dimension(7, 23));

        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 1600, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(deptMemberSearchComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(searchDepartmentTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(searchButton)
                        .addGap(515, 515, 515)
                        .addComponent(refreshButton, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(personalInfoBotton, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(logoutBotton, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 760, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(deptMemberSearchComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchDepartmentTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchButton)
                    .addComponent(refreshButton, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(personalInfoBotton, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logoutBotton, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        logoutBotton.getAccessibleContext().setAccessibleName("logoutButton");
        personalInfoBotton.getAccessibleContext().setAccessibleName("personInfoBotton");
    }// </editor-fold>//GEN-END:initComponents

    private void logoutBottonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutBottonMouseClicked
        logout();
    }//GEN-LAST:event_logoutBottonMouseClicked

    private void personalInfoBottonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personalInfoBottonActionPerformed
    
    }//GEN-LAST:event_personalInfoBottonActionPerformed

    private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButtonActionPerformed
        refreshTaskTable();
    }//GEN-LAST:event_refreshButtonActionPerformed

    private void logoutBottonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBottonActionPerformed
        
    }//GEN-LAST:event_logoutBottonActionPerformed

    private void personalInfoBottonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_personalInfoBottonMouseClicked
        new SubFrame().showSubPanelUI();  
    }//GEN-LAST:event_personalInfoBottonMouseClicked

    private void deptMemberSearchComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deptMemberSearchComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deptMemberSearchComboBoxActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        searchTask();
    }//GEN-LAST:event_searchButtonActionPerformed

    private void searchTask(){
        String inputValue = searchDepartmentTextField.getText();
        System.out.println("Search Task : "+inputValue);
        cleanTableModel(taskTable);
        switch(deptMemberSearchComboBox.getSelectedIndex()){
            case 0: // ALL task
                getStaffTaskTableModel(projectDao.taskListForProjectMember(loginEmployee.getEmployee_no(),SearchSelection.ALL, null) ,taskTable);
                break;
            case 1:// project id
                getStaffTaskTableModel(projectDao.taskListForProjectMember(loginEmployee.getEmployee_no(),SearchSelection.PROJECT_ID, inputValue) ,taskTable);
                break;
            case 2: // Project name
                getStaffTaskTableModel(projectDao.taskListForProjectMember(loginEmployee.getEmployee_no(),SearchSelection.PROJECT_NAME, inputValue) ,taskTable);
                break;
            case 3:// project_leader_id
                getStaffTaskTableModel(projectDao.taskListForProjectMember(loginEmployee.getEmployee_no(),SearchSelection.PROJECT_LEADER_ID, inputValue) ,taskTable);
                break;
            case 4:// project still processing
                getStaffTaskTableModel(projectDao.taskListForProjectMember(loginEmployee.getEmployee_no(),SearchSelection.PROJECT_STILL_PROCESSING, null) ,taskTable);
                break;
            case 5:// project end
                getStaffTaskTableModel(projectDao.taskListForProjectMember(loginEmployee.getEmployee_no(),SearchSelection.PROJECT_ENDED, null) ,taskTable);
                break;
            default: 
                System.out.println("What are you looking for");
                break;
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> deptMemberSearchComboBox;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton logoutBotton;
    private javax.swing.JButton personalInfoBotton;
    private javax.swing.JButton refreshButton;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextField searchDepartmentTextField;
    private javax.swing.JTable taskTable;
    // End of variables declaration//GEN-END:variables

    


  
}
